Add git diff timeout in app config
gogs/gogs pull request #6348
Opened 2020-09-24 21:05 UTC by zhukovra

Resolve #6315

2020-09-26 14:13 UTC, unknwon requested changes
Thanks!

Changes LGTM.

Please run a `go generate internal/assets/conf/conf.go` and add a [CHANGELOG](https://github.com/gogs/gogs/blob/main/CHANGELOG.md) entry under **Added** section.

2020-09-28 18:52 UTC, zhukovra commented
@unknwon all done

2020-09-29 15:06 UTC, unknwon approved these changes

2020-09-29 15:06 UTC, unknwon commented on CHANGELOG.md
> +- Configuration option `DIFF` added to `[git.timeout]` section.
```suggestion
- Add new configuration option `[git.timeout] DIFF` for customizing operation timeout of `git diff`. [#6315](https://github.com/gogs/gogs/issues/6315)
```

2020-09-29 15:12 UTC, merged