Refactor pull #6349
gogs/gogs pull request #6350
Opened 2020-09-25 12:26 UTC by laojianzi

Refactor pull #6349

2020-09-27 02:19 UTC, unknwon requested changes
Thanks! Please see inline comments.

2020-09-27 02:19 UTC, unknwon commented on internal/db/repo.go
> +	}
We do not need to re-create metas map every time this method is being called:
```suggestion
	if repo.ExternalMetas != nil {
		return repo.ExternalMetas
	}
	
	repo.ExternalMetas = make(map[string]string)
```

2020-09-27 02:19 UTC, unknwon commented on internal/markup/markup.go
> +		return fmt.Sprintf(`<a href="%s/commit/%s"><code>%s</code></a>`, urlPrefix, m, tool.ShortSHA1(m))
Since this link is broken anyway for SHA1 links, I don't think this fall back does any good, thus can remove it.

2020-09-27 02:19 UTC, unknwon commented on internal/db/repo.go
> +	repo.ExternalMetas["repo"] = repo.Name
Use the result of [`repo.Link`](https://github.com/gogs/gogs/blob/211a1394b86dafc90d73d5d622ca85686c2fb5f6/internal/db/repo.go#L544-L546) is better here, that's all we want.
```suggestion
	repo.ExternalMetas["repoLink"] = repo.Link()
```

2020-09-27 02:19 UTC, unknwon commented on internal/markup/markup.go
> +		}
It is generally safe to assume `metas` won't be empty.

```suggestion
		return fmt.Sprintf(`<a href="%s/commit/%s"><code>%s</code></a>`, metas["repoLink"], m, tool.ShortSHA1(string(m)))
```

2020-09-27 02:19 UTC, unknwon commented on internal/markup/markup.go
> +	rawBytes = RenderSha1CurrentPattern(rawBytes, urlPrefix, metas)
In fact, I think the only change we need in this file is this:

```suggestion
	rawBytes = RenderSha1CurrentPattern(rawBytes, metas["repoLink"])
```

2020-09-27 07:56 UTC, laojianzi commented
> Thanks! Please see inline comments.

Thanks for your review!

2020-09-29 14:56 UTC, unknwon approved these changes
Thank you!

2020-09-29 15:02 UTC, unknwon commented
@laojianzi If you're interested, the next step would be refactor the repository metas to be a concrete struct, instead of a `map[string]string`.

2020-09-29 15:07 UTC, merged

2020-10-14 11:54 UTC, laojianzi commented
> @laojianzi如果您有兴趣，下一步将是将存储库meta重构为一个具体的结构，而不是一个`map[string]string`。

@unknwon Nice, @me 👍